# Generated by Django 5.0.6 on 2025-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('anon_username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('entrance_exam', models.CharField(blank=True, max_length=50, null=True)),
                ('entrance_score', models.FloatField(blank=True, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True)),
                ('desired_course', models.CharField(blank=True, max_length=100, null=True)),
                ('aptitude_score', models.FloatField(blank=True, null=True)),
                ('interest_mapping', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
