# Generated by Django 5.0.6 on 2025-03-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='student_id',
            new_name='id',
        ),
    ]
