# Generated by Django 5.0.6 on 2025-03-29 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('students', '0004_rename_student_id_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='anon_username',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type', 'is_active'], name='students_cu_user_ty_dead82_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['cgpa', 'entrance_score'], name='students_cu_cgpa_c6ac81_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['preferred_location', 'desired_course'], name='students_cu_preferr_7b016a_idx'),
        ),
    ]
