# Generated by Django 5.0.6 on 2025-06-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_customuser_preferred_city_customuser_tenth_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category_score_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
