# Generated by Django 5.0.6 on 2025-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_customuser_category_score_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='graduation_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postgraduation_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
