# Generated by Django 5.0.6 on 2025-03-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='admin_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
