# Generated by Django 5.0.6 on 2025-03-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_adminuser_is_admin_adminuser_admin_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='admin_role',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
