# Generated by Django 5.0.6 on 2025-06-02 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_adminuser_options_alter_testquestion_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychometricQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('dimension', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PsychometricOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='admin_app.psychometricquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PsychometricAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.psychometricoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.psychometricquestion')),
            ],
        ),
    ]
