# Generated by Django 5.0.6 on 2025-06-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_collegetype_course_college_collegecourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='average_package',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='entrance_exams',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
