# Generated by Django 5.0.6 on 2025-06-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_college_average_package_college_entrance_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='institute_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
