# Generated by Django 5.0.6 on 2025-06-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_college_institute_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegecourse',
            name='selection_criteria',
            field=models.TextField(blank=True),
        ),
    ]
